[package]
name = "pitch-toy"
version = "0.1.0"
edition = "2021"
description = "Real-time pitch detection with Rust/WASM and Web Audio API"
repository = "https://github.com/user/pitch-toy"
license = "MIT"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
web-sys = { version = "0.3", features = [
  "console",
  "Performance",
  "Window",
  "Document",
  "Element",
  "HtmlCanvasElement",
] }
pitch-detection = "0.3"
rustfft = "6.0"
wasm-bindgen = "0.2"

# Development dependencies
console_error_panic_hook = "0.1"

[lib]
crate-type = ["cdylib"]
