[package]
name = "pitch-visualizer"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Real-time pitch visualizer with interval analysis for web browsers"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
# WASM Bindings
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "AudioContext",
  "AudioWorklet",
  "AudioWorkletNode",
  "MediaStream",
  "MediaDevices",
  "Navigator",
  "AudioBuffer",
  "AudioParam",
  "AudioNode",
  "BaseAudioContext",
  "OfflineAudioContext",
  "GainNode",
  "OscillatorNode",
  "AnalyserNode",
] }

# Audio Processing (kept for DSP algorithms)
pitch_detection = "0.4"

# Math & Utilities
bytemuck = "1.14"                # Safe transmutation
anyhow = "1.0"                   # Error handling
thiserror = "1.0"                # Error derive macros
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"      # Efficient serialization for WASM/JS boundary

# WASM-specific utilities
wasm-bindgen-futures = "0.4"    # Async support
getrandom = { version = "0.2", features = ["js"] }  # Random number generation in WASM

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "AudioContext",
  "AudioWorklet",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"       # Testing in browsers

[profile.release]
lto = true
opt-level = "s"                  # Optimize for size (important for WASM)
panic = "abort"
strip = true

[profile.dev]
opt-level = 1                    # Slight optimization for audio performance 