[package]
name = "hello-yew"
version = "0.1.0"
edition = "2021"
description = "Real-time pitch detection with Rust/WASM and Web Audio API"
repository = "https://github.com/user/pitch-toy"
license = "MIT"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib"]
