# 🛠️ Development Build Configuration
# Optimized for development workflow with full debugging capabilities

[build]
profile = "dev"
target = "web"
debug = true
source_maps = true
optimization_level = "0"

[wasm]
debug_symbols = true
name_section = true
producers_section = true
debug_info = true

[features]
# Development features
debug_logging = true
performance_profiling = true
memory_debugging = true
connection_validation = true
audio_analysis_logging = true
wasm_interface_validation = true

# Enhanced development tools
hot_reload_support = true
development_ui = true
debug_overlays = true
performance_monitors = true

[javascript]
minification = false
source_maps = true
debug_mode = true
console_logging = "verbose"

[audio]
# Development audio settings
buffer_sizes = [128, 256, 512, 1024, 2048]
sample_rates = [22050, 44100, 48000, 96000]
latency_target_ms = 50
enhanced_validation = true

[output]
directory = "dist/development"
wasm_file = "pitch_toy_dev.wasm"
js_file = "pitch_toy_dev.js"
include_test_framework = true 