[build]
target = "index.html"
dist = "dist/development"
public-url = "/"

[watch]
watch = ["src"]
ignore = ["target", "dist"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

[tools]
wasm-bindgen = "0.2"