# 🚀 Production Build Configuration  
# Optimized for maximum performance and minimal bundle size

[build]
profile = "release"
target = "web"
debug = false
source_maps = false
optimization_level = "3"

[wasm]
# Maximum optimization
debug_symbols = false
name_section = false
producers_section = false
debug_info = false
strip_debug = true
optimize_for_size = true

# Advanced optimizations
lto = true
codegen_units = 1
panic = "abort"

[features]
# Production features only
debug_logging = false
performance_profiling = false
memory_debugging = false
connection_validation = false
audio_analysis_logging = false
wasm_interface_validation = false

# Essential production features
error_reporting = true
performance_monitoring = true
basic_validation = true

[javascript]
minification = true
source_maps = false
debug_mode = false
console_logging = "error"
tree_shaking = true
compression = "gzip"

[audio]
# Optimized audio settings
buffer_sizes = [1024]  # Single optimized buffer size
sample_rates = [44100] # Standard sample rate
latency_target_ms = 30 # Aggressive latency target
enhanced_validation = false

[output]
directory = "dist/production"
wasm_file = "pitch_toy.wasm"
js_file = "pitch_toy.min.js"
include_test_framework = false

[optimization]
# Aggressive optimization flags
wasm_opt_level = "Oz"  # Optimize for size
strip_unused = true
merge_functions = true
inline_functions = true
dead_code_elimination = true 